spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: #
    password: #
    url: jdbc:mysql://localhost:3306/newnews?
  jpa:
    hibernate:
    ddl-auto: create
  properties:
    hibernate:
    show_sql: true
    format_sql: true